### ISSUE TITLE
Bux reports back: Unauthorized

### ISSUE THREAD

**Issue by jonathanlang** [v-morlock/bux-moneymoney#2]
Update needed?

**Comment by jonathanlang** [comment]
@v-morlock are you seeing the same thing by any chance? Or is this project abandoned?

**Comment by v-morlock** [comment]
Hi, 

excuse my late reply. I've been getting the same error but could fix it by re-authenticating (right click & "zugangsdaten bearbeiten").

Hope that helps, otherwise let me know!

Best, 
Valentin
